name: pipeline
on: push
jobs:
 checkout:
   name: checkout-code
   runs-on: ubuntu-latest
   steps:
    - name: first-step
      uses: actions/checkout@v4
    -  name: second-step
       run: |
        python hello.py
   
 create-artifact:
    name: create-artifacts
    runs-on: ubuntu-latest
